resources:
- manager.yaml

images:
- name: controller
  newName: ghcr.io/etclank/cloud-native-service-control-plane-operator
  digest: sha256:8b537b3ab1780141b2554e495f7dd72ab36f7eb4d37c7ed396ebfa0d7cc88eb4
