resources:
- manager.yaml

images:
- name: controller
  newName: ghcr.io/etclank/cloud-native-service-control-plane-operator
  digest: sha256:a1265442af429340cb6cddf078cdec4b021bceb1d171215ad55fbccf7bfb4391
