# This rule is not used by the project platform-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.eoghanclancy.eu resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedservice-viewer-role
rules:
- apiGroups:
  - platform.eoghanclancy.eu
  resources:
  - managedservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.eoghanclancy.eu
  resources:
  - managedservices/status
  verbs:
  - get
