---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.eoghanclancy.eu
  resources:
  - managedservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.eoghanclancy.eu
  resources:
  - managedservices/finalizers
  verbs:
  - update
- apiGroups:
  - platform.eoghanclancy.eu
  resources:
  - managedservices/status
  verbs:
  - get
  - patch
  - update
