apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - network-policy-traefik.yaml
  - certificate.yaml
  - middleware.yaml
  - ingress.yaml
