apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-api
  namespace: platform-system
  labels:
    app.kubernetes.io/name: control-plane-api
    app.kubernetes.io/part-of: cloud-native-service-control-plane
automountServiceAccountToken: true
