{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-dns-egress
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: cloud-native-service-control-plane
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-kubernetes-api-egress
  namespace: observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: cloud-native-service-control-plane
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{ required "networkPolicyDestinations.kubernetesAPI.cidr is required" .Values.networkPolicyDestinations.kubernetesAPI.cidr }}
      ports:
        - port: {{ required "networkPolicyDestinations.kubernetesAPI.port is required" .Values.networkPolicyDestinations.kubernetesAPI.port }}
          protocol: TCP
{{- end }}
