apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: cloud-native-service-control-plane
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: agent-collector
  ports:
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: otlp
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
