apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: cloud-native-service-control-plane
automountServiceAccountToken: false
